### PR TITLE
Adjust the variable parsing for `vrb` argument

### LINKED ISSUE #145: vrb in `plot_trace` with external vector not working
Hello,

When using the plot_trace function, one cannot use a vector even though it has a string. The documentation mentions one can use a vector, however.

Here is my code: 

`var<-"measure1"` 
`plot_trace(data = imp, vrb = var)`

This yields an error:

Error in `dplyr::select()`:
! Can't subset columns that don't exist.
✖ Column `var` doesn't exist.

When checking the plot_trace function itself, I noticed it uses substitute inside. I think that is the problem, although not entirely sure. It is probably my lack of familiarity with the substitute function.

Any help would be appreciated!

### PR DESCRIPTION
**Pull request by kylelang**
This PR tweaks the way the `vrb` argument is parsed for `plot_trace()`. In particular, it makes the function work when an external object is supplied as the function argument. In such cases, the object name will need to be unquoted using `!!`. I've attempted to align the implementation with standard Tidy Evaluation principles. Hence, requiring the `!!`-based unquoting rather than adjusting `plot_trace()` to gobble up all sensible inputs.

The documentation and unit tests should reflect the relevant changes.

This PR should fix #145.

### CODE REVIEW

File: R/plot_trace.R [hunk 1]
```diff
@@ -3,11 +3,40 @@
...
+#' ## When passing the variable names as an object from the environment, the
+#' ## object's name must be unqoted via `!!`.
+#' vars <- c("bmi", "hyp")
+#' plot_trace(imp, vars) |> try() # Error
+#' plot_trace(imp, !!vars)        # Runs because the 'vrb' argument is unquoted
+#'
+#' for(v in vars)
+#'   plot_trace(imp, !!v) |> print()
+#'
+#' @importFrom utils tail
```
Comment (hanneoberman) [inline R/plot_trace.R:38]: `ggmice` adheres to the https://r-pkgs.org/ recommendation of using `::` for imported functions instead of `importFrom`

File: R/plot_trace.R [hunk 2]
```diff
@@ -3,11 +3,40 @@
...
+#' @importFrom rlang enexpr
```
Comment (hanneoberman) [inline R/plot_trace.R:39]: idem, using `::` instead of `importFrom`

File: R/plot_trace.R [hunk 3]
```diff
@@ -20,14 +49,27 @@ plot_trace <- function(data, vrb = "all") {
   sm <- sqrt(data$chainVar)
 
   # select variable to plot from list of imputed variables
-  vrb <- substitute(vrb)
+  vrb <- enexpr(vrb)
+  if(is.call(vrb))
```
Comment (hanneoberman) [inline R/plot_trace.R:53]: lint: adding space after `if`

File: R/plot_trace.R [hunk 4]
```diff
@@ -20,14 +49,27 @@ plot_trace <- function(data, vrb = "all") {
...
+    vrb <- as.character(vrb) |> tail(-1)
+  else if(is.symbol(vrb))
```
Comment (hanneoberman) [inline R/plot_trace.R:55]: lint: idem, adding space

File: R/plot_trace.R [hunk 5]
```diff
@@ -20,14 +49,27 @@ plot_trace <- function(data, vrb = "all") {
   sm <- sqrt(data$chainVar)
 
   # select variable to plot from list of imputed variables
-  vrb <- substitute(vrb)
+  vrb <- enexpr(vrb)
+  if(is.call(vrb))
+    vrb <- as.character(vrb) |> tail(-1)
```
Comment (hanneoberman) [inline R/plot_trace.R:54]: adding extra comment here to explain *why*

File: R/plot_trace.R [hunk 6]
```diff
@@ -20,14 +49,27 @@ plot_trace <- function(data, vrb = "all") {
...
     vrb <- varlist
-  } else {
-    vrb <- names(dplyr::select(data$data, {{vrb}}))
+  } else if (any(vrb %nin% colnames(data$data))) {
+    cli::cli_abort(
+      c(
+        "x" = "The following variables are not present in 'data':",
+        " " = paste(setdiff(vrb, colnames(data$data)), collapse = ", "),
+        "i" = "Did you forget to use `!!` to unqote the object name you passed to the `vrb` argument?",
+        "i" = "Or maybe you just made a typo?"
```
Comment (hanneoberman) [inline R/plot_trace.R:68]: Love this!

**Review by hanneoberman — COMMENTED** [review]
Hi Kyle, thank you VERY much for this PR. I'll fix some small styling things locally. But otherwise no notes!

**Comment by hanneoberman** [comment]
Not merging this yet, because the proposed solution should first work in all `ggmice::plot_*` functions.

**Review by hanneoberman — APPROVED** [review]
